#!/bin/bash
scriptname=$(basename $0)

keyfile="$2"
if [[ -z "$keyfile" ]]; then keyfile="$HOME/.otpkeys"; fi
findfile=0
if cat "$keyfile" > /dev/null 2>&1; then
	findfile=0
else
	findfile=1
fi


scriptdir="${BASH_SOURCE%/*}"
if [[ ! -d "$scriptdir" ]]; then scriptdir="$PWD"; fi

if [[ ! $findfile -eq 0 ]]
then
	echo "No keyfile found. "
	echo "Currently looking for "
	echo "      $keyfile"
	echo " but it is not there"
	echo ""
	echo "Fixes: Either create the file or specify a keyfile"
	echo "with" 
	echo "     ./otp keyname keyfile"
	exit
fi

if [ -z $1 ]
then
    echo "$scriptname: Service Name Needed"
    echo ""
    echo "Usage:"
	echo "   otp keyname (keyfile)"
	echo ""
	echo "Examples:"
	echo "   otp google"
	echo "   otp google mykeyfile"
    echo ""
    echo "Configuration: $keyfile"
    echo "Format: name=key"
    exit
fi
otpkey=$(cat "$keyfile" | grep "$1" | cut -d"=" -f 2 | sed "s/ //g")
if [ -z "$otpkey" ]
then
    echo "$scriptname: Bad Service Name"
    exit
fi
/usr/bin/python "$scriptdir/token.py" --totp "$otpkey"
