#!/bin/bash
scriptname=$(basename $0)
keyfile="$HOME/.otpkeys"
if [ -z $1 ]
then
    echo "$scriptname: Service Name Needed"
    echo ""
    echo "Usage:"
    echo "   otp google"
    echo ""
    echo "Configuration: $HOME/.otpkeys"
    echo "Format: name=key"
    exit
fi
otpkey=$(cat "$keyfile" | grep "$1" | cut -d"=" -f 2 | sed "s/ //g")
if [ -z "$otpkey" ]
then
    echo "$scriptname: Bad Service Name"
    exit
fi
/usr/bin/python token.py --totp "$otpkey"
